name: tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    environment: esivalvoja-testing
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: development
      DISCORD_TOKEN_DEVELOPMENT: ${{ secrets.DISCORD_TOKEN_DEVELOPMENT }}
      DISCORD_TEST_CLIENT_TOKEN: ${{ secrets.DISCORD_TEST_CLIENT_TOKEN }}
      BOT_KILL_COMMAND: ${{ secrets.BOT_KILL_COMMAND }}
      DISCORD_TEST_CHANNEL_ID: ${{ secrets.DISCORD_TEST_CHANNEL_ID }}
      DISCORD_DEV_BOT_ID: ${{ secrets.DISCORD_DEV_BOT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Update pip
        run: python3 -m pip install --upgrade pip
      - name: Install Python packages
        run: pip3 install -r requirements.txt

      - name: Type checking
        run: mypy main.py

      - name: Run tests
        run: nose2 -v

      - name: Run Discord integration tests
        run: app/tests_discord/test_discord_full_integration.sh


